from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from app.models.device import ScanReport
from app.database.database import get_db
import sqlite3
from app.routes.auth import RoleChecker
from typing import List, Optional
import csv
import io
import datetime

router = APIRouter()

@router.get("/", response_model=List[ScanReport])
def list_reports(
    current_user: dict = Depends(RoleChecker(["network_admin", "network_operator"])),
    conn: sqlite3.Connection = Depends(get_db)
):
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM reports ORDER BY timestamp DESC")
    rows = cursor.fetchall()
    return [dict(row) for row in rows]

@router.get("/export/csv")
def export_reports_csv(
    current_user: dict = Depends(RoleChecker(["network_admin", "network_operator"])),
    conn: sqlite3.Connection = Depends(get_db)
):
    """Exports all scan reports as a downloadable CSV file."""
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM reports ORDER BY timestamp DESC")
    rows = cursor.fetchall()

    output = io.StringIO()
    writer = csv.writer(output)

    # Header row
    writer.writerow(["ID", "Timestamp", "Devices Found", "Active Devices", "Scan Duration (s)", "Summary"])

    for row in rows:
        writer.writerow([
            row["id"],
            row["timestamp"],
            row["devices_found"],
            row["active_devices"],
            row["scan_duration_secs"],
            row["summary"] or ""
        ])

    output.seek(0)
    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": "attachment; filename=recon_nds_scan_reports.csv"}
    )

@router.get("/export/devices-pdf")
def export_devices_pdf(
    current_user: dict = Depends(RoleChecker(["network_admin", "network_operator"])),
    conn: sqlite3.Connection = Depends(get_db)
):
    """
    Generates and downloads a styled PDF device inventory report using fpdf2.
    Includes a summary cover page and a full device inventory table.
    """
    try:
        from fpdf import FPDF
    except ImportError:
        from fastapi import HTTPException
        raise HTTPException(status_code=500, detail="fpdf2 library not available. Install it via: pip install fpdf2")

    try:
        cursor = conn.cursor()

        # --- Gather statistics ---
        cursor.execute("SELECT COUNT(*) as total FROM devices")
        total_devices = cursor.fetchone()["total"]

        cursor.execute("SELECT COUNT(*) as c FROM devices WHERE status = 'active'")
        active_devices = cursor.fetchone()["c"]

        cursor.execute("SELECT COUNT(*) as c FROM devices WHERE is_trusted = 1")
        trusted_devices = cursor.fetchone()["c"]

        cursor.execute("SELECT COUNT(*) as c FROM devices WHERE trust_level = 'Blocked'")
        blocked_devices = cursor.fetchone()["c"]

        cursor.execute("SELECT COUNT(DISTINCT device_id) as c FROM device_cves")
        vulnerable_devices = cursor.fetchone()["c"]

        # --- Fetch all devices ---
        cursor.execute("""
            SELECT id, ip, mac, hostname, vendor, os_type, status, trust_level,
                   department, owner_name, firmware_version, firmware_eol,
                   site_location, vlan, last_seen
            FROM devices
            ORDER BY trust_level ASC, status DESC, hostname ASC
        """)
        devices = cursor.fetchall()

        # --- Build PDF ---
        pdf = FPDF(orientation="L", unit="mm", format="A4")
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.set_margins(10, 10, 10)

        # ── Cover / Summary Page ─────────────────────────────────────
        pdf.add_page()

        # Title block
        pdf.set_fill_color(15, 23, 42)   # dark navy
        pdf.rect(0, 0, 297, 45, "F")
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 22)
        pdf.set_xy(10, 10)
        pdf.cell(0, 10, "Recon NDS — Network Device Inventory Report", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_xy(10, 26)
        generated_at = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        pdf.cell(0, 8, f"Generated: {generated_at}  |  Generated by: {current_user.get('username', 'system')}", ln=True)

        # Summary stats
        pdf.set_text_color(30, 30, 30)
        pdf.set_xy(10, 55)
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "Executive Summary", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.ln(2)

        stats = [
            ("Total Devices",     total_devices),
            ("Active Devices",    active_devices),
            ("Trusted Devices",   trusted_devices),
            ("Blocked Devices",   blocked_devices),
            ("Devices with CVEs", vulnerable_devices),
        ]
        col_w = 55
        for label, val in stats:
            pdf.set_fill_color(241, 245, 249)
            pdf.cell(col_w, 10, f"  {label}", border=0, fill=True)
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(25, 10, str(val), border=0, fill=True, ln=False)
            pdf.set_font("Helvetica", "", 11)
            pdf.ln(12)

        # ── Device Inventory Table ───────────────────────────────────
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, "Device Inventory", ln=True)
        pdf.ln(2)

        # Table header
        headers = ["IP Address", "Hostname", "MAC", "Vendor", "Type", "Status",
                   "Trust", "Department", "Owner", "Firmware", "Location", "Last Seen"]
        col_widths = [28, 35, 32, 32, 20, 18, 18, 28, 28, 22, 28, 30]

        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(15, 23, 42)
        pdf.set_text_color(255, 255, 255)
        for h, w in zip(headers, col_widths):
            pdf.cell(w, 7, h, border=0, fill=True)
        pdf.ln()

        # Table rows
        pdf.set_font("Helvetica", "", 7.5)
        row_fill = False
        for dev in devices:
            # Row background alternates
            if row_fill:
                pdf.set_fill_color(241, 245, 249)
            else:
                pdf.set_fill_color(255, 255, 255)
            row_fill = not row_fill

            # Trust-level color coding for text
            trust = dev["trust_level"] or "Unknown"
            if trust == "Blocked":
                pdf.set_text_color(185, 28, 28)
            elif trust == "Unknown" or trust == "Pending":
                pdf.set_text_color(146, 64, 14)
            else:
                pdf.set_text_color(30, 30, 30)

            fw = (dev["firmware_version"] or "") + (" [EOL]" if dev["firmware_eol"] else "")
            last_seen_str = str(dev["last_seen"] or "")[:16]

            row_vals = [
                dev["ip"] or "",
                (dev["hostname"] or "")[:28],
                (dev["mac"] or "")[:20],
                (dev["vendor"] or "")[:22],
                dev["os_type"] or "generic",
                dev["status"] or "",
                trust,
                (dev["department"] or "")[:18],
                (dev["owner_name"] or "")[:18],
                fw[:18],
                (dev["site_location"] or "")[:20],
                last_seen_str,
            ]
            for val, w in zip(row_vals, col_widths):
                pdf.cell(w, 6, str(val), border=0, fill=True)
            pdf.ln()

            # Reset text color after each row
            pdf.set_text_color(30, 30, 30)

        # ── CVE Summary Section ───────────────────────────────────────
        cursor.execute("""
            SELECT d.hostname, d.ip, d.vendor, d.firmware_version,
                   dc.cve_id, dc.severity, dc.cvss_score, dc.description
            FROM device_cves dc
            JOIN devices d ON dc.device_id = d.id
            ORDER BY dc.cvss_score DESC
            LIMIT 30
        """)
        cve_rows = cursor.fetchall()

        if cve_rows:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(0, 8, "Top CVE Vulnerabilities", ln=True)
            pdf.ln(2)

            cve_headers = ["CVE ID", "Severity", "CVSS", "Hostname", "IP", "Vendor", "Firmware", "Description"]
            cve_widths  = [28, 18, 12, 35, 28, 30, 25, 101]

            pdf.set_font("Helvetica", "B", 8)
            pdf.set_fill_color(185, 28, 28)
            pdf.set_text_color(255, 255, 255)
            for h, w in zip(cve_headers, cve_widths):
                pdf.cell(w, 7, h, border=0, fill=True)
            pdf.ln()

            pdf.set_font("Helvetica", "", 7.5)
            row_fill = False
            for cve in cve_rows:
                if row_fill:
                    pdf.set_fill_color(255, 235, 235)
                else:
                    pdf.set_fill_color(255, 255, 255)
                row_fill = not row_fill

                severity = cve["severity"] or "Unknown"
                score    = f"{cve['cvss_score']:.1f}" if cve["cvss_score"] is not None else "-"

                # Color-code severity
                if severity in ("Critical",):
                    pdf.set_text_color(185, 28, 28)
                elif severity == "High":
                    pdf.set_text_color(194, 65, 12)
                else:
                    pdf.set_text_color(30, 30, 30)

                row_vals = [
                    cve["cve_id"] or "",
                    severity,
                    score,
                    (cve["hostname"] or "")[:28],
                    cve["ip"] or "",
                    (cve["vendor"] or "")[:22],
                    (cve["firmware_version"] or "")[:18],
                    (cve["description"] or "")[:90],
                ]
                for val, w in zip(row_vals, cve_widths):
                    pdf.cell(w, 6, str(val), border=0, fill=True)
                pdf.ln()
                pdf.set_text_color(30, 30, 30)

        # Output PDF as bytes
        pdf_bytes = pdf.output()
        filename  = f"recon_nds_inventory_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        return StreamingResponse(
            io.BytesIO(bytes(pdf_bytes)),
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
    finally:
        pass

